print("konichiwa")
print("vikas","pandey") #print(yamada san)
print("how are u") #print(san)
print() 
print("genki") #print(yamada)
print("k26A2501") 
print ("vikas","pandey") #print("パン","ビカス")
print("sketching") #print("絵を描くこと")
name=input("vikas")
print("namaste,"+name+"!")